config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'profiles/index'
  root to: "profiles#index"
  resources :profiles
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  
  validates :message, presence: true
  validates :age, presence: true
  validates :career, presence: true
  validates :image, presence: true

  belongs_to :user
  has_one_attached :image

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_one :profile

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,only:[:new,:edit,:destroy]
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!,only:[:new,:edit,:destroy]
  before_action :move_to_index, except: [:index,:show,:new,:create]


  def index
    @profile= Profile.order("updated_at DESC")
  end

  def new
   @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save
    redirect_to root_path
    else
    render :new
    end
   
  end

def show
  @profile= Profile.find(params[:id])
end 

def edit
  @profile= Profile.find(params[:id])
end

def update
  @profile = Profile.find(params[:id])
  if @profile.update(profile_params)
    redirect_to root_path
  else
    render :edit
  end
end

def destroy
  @profile = Profile.find(params[:id])
  @profile.destroy
  redirect_to root_path
end



private

 def profile_params
   params.require(:profile).permit(:message, :age, :career, :image).merge(user_id: current_user.id)
 end

 def move_to_index
   @profile = Profile.find(params[:id])
   unless current_user.id == @profile.user.id
     redirect_to action: :index
   end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FROM_WHO</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>

   <%# 社員と顧客をidによって分岐させる %>
  <% if user_signed_in? && current_user.id <= 10 %> <%#>herokuでは104 ローカルでは10<%>
      <header class="sales_header">
    <% elsif user_signed_in? && current_user.id >= 11%> <%#>herokuでは105 ローカルでは11<%>
      <header class="customer_header">
    <% else %>
      <header class="customer_header">
  <% end %>
<%# 社員と顧客をidによって分岐させる %>


      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>


          <%if user_signed_in? %>
                  <div class="nav__right"> 
                    <%= link_to "ログアウト",  destroy_user_session_path,  method: :delete, class: :nav__logout %>
              <%# ↓すでに投稿している社員だったら %>  
                  <% if  current_user.profile.present? && current_user.id <= 10 %> <%#>herokuでは104 ローカルでは10<%>
                  <%= link_to "自分のプロフィールを見る", profile_path(current_user.profile.id), class: :nav__btn %>
              <%# ↓投稿していない社員だったら %> 
                    <% elsif user_signed_in? && current_user.id <= 10 %> <%#>herokuでは104 ローカルでは10<%>
                  <%= link_to "プロフィールの投稿", new_profile_path, class: :nav__btn %>
                    <% else %>
              <%# 顧客の場合の実装時記述 %>
                  <% end %>
           
              </div> 
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
  
<%# 社員と顧客をidによって分岐させる %>
  <% if user_signed_in? && current_user.id <= 10 %>  <%#>herokuでは104 ローカルでは10<%>
    <footer class="sales_footer">
    <p class="sales_footer_letter">社員用のページです。</p>
    <% elsif user_signed_in? && current_user.id >= 11%> <%#>herokuでは105 ローカルでは11<%>
     <footer class="customer_footer">
    <p class="customer_footer_letter">当社をご利用いただきありがとうございます。</p>
    <% else %>
  <% end %>
<%# 社員と顧客をidによって分岐させる %>


    </footer>
  </body>
</html>

app/views/profiles/_form.html.erb
<% if user_signed_in? && current_user.id <= 11 %>   <%#>herokuでは104 ローカルでは11<%>
    <%= form_with model: profile, local: true do |f|%>
      <div class="field">
        <%= f.label :image, "セールスの画像" %><br />
        <%= f.file_field :image, id:"profile_image" %>
      </div>

      <div class="field">
        <%= f.label :message, "お客様へのメッセージ" %><br />
        <%= f.text_area :message,class: :form__message, id:"profile_massage" %>
      </div>

      <div class="field">
        <%= f.label :age, "年齢" %><br />
        <%= f.text_area :age,class: :form__age, id:"profile_age" %>歳
      </div>

      <div class="field">
        <%= f.label :career, "経歴やコメント" %><br />
        <%= f.text_area :career, class: :form__text, id:"profile_career" %>
      </div>

      <div class="actions">
        <%= f.submit "保存する", class: :form__btn  %>
      </div>

    <% end %>

  <%# elsif user_signed_in? && current_user.id >= 11%>
  <%#顧客のプロフィールを実装する時に記述%>
  <%#else %>
 


<%end %>

app/views/profiles/_profile.html.erb
<% if user_signed_in?%>

    <div class="card">
        <p class="card__summary">
        <%= profile.user.name %>
        </p>
        <%= link_to image_tag(profile.image, class: :card__img ), profile_path(profile.id)%>
        <div class="card__body">
        <%#= link_to profile.message, profile_path(profile.id),method: :get, class: :card__title%>
        <p class="card__summary">
        <%= profile.age %>歳
        </p>
        <p class="card__summary">
        <%= profile.career %>
        </p>
        <%#= link_to profile.user.name, user_path(profile.user.id), class: :card__user %>
      </div>
    </div>

<% end %>

app/views/profiles/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">社員プロフィール編集</h2>
       <%= render partial: "form", locals: { profile: @profile } %>
    </div>
  </div>
</div>

app/views/profiles/index.html.erb
<main class="main">
  <div class="inner">
 

<% if user_signed_in? %>
    <div class="card__wrapper">
      <%= render partial: "profile", collection: @profile %>    
    </div>

<div ><%#= "#{current_user.id}さん"%>
</div>



<% else %>
   <div class="topimage">
      <%= render partial: "profile", collection: @profile %>    
   </div>
<% end %>


  </div>
</main>

app/views/profiles/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">お客様へのプロフィール投稿</h2>
        <%= render partial: "form", locals: { profile: @profile } %>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<main class="main">
  <div class="inner">
    <div class="profile__wrapper">
      
       <% if user_signed_in? && current_user.id == @profile.user_id %>
        <div class="sekuhen">
            <div class="profile__manage">
              <%= link_to "編集する", edit_profile_path(@profile.id), class: :profile__btn %>
            </div>
              <div class="profile__manage">
              <%= link_to "削除する", profile_path(@profile.id), method: :delete ,class: :profile__btn %>
            </div>
        </div>
      <% end %>

     <%#名前と画像を左側に。その他を右側に配置する。%>
     <div class="head">
      <div class="head-left"> 
        <p class="profile__hedding">
            <%= @profile.user.name %>
          </p>
          <div class="profile__image">
            <%= image_tag @profile.image %>
          </div>
           <% if current_user.id != @profile.user_id && current_user.id >= 11 %>
           <div class="renraku-button">
            この社員に連絡をしてみる。
           </div>
           <% elsif current_user.id == @profile.user_id %> 
            <div class="renraku-button">
            お客様からの問い合わせ一覧
           </div>
           <% else %>

           <% end %>

      </div>

      <div class="head-right">
              <div class="profile__detail">
              <p class="detail__title">年齢</p>
                <p class="detail__message">
                  <%= @profile.age %>歳
                </p>
              </div>
              <div class="profile__detail">
                <p class="detail__title">経歴</p>
                <p class="detail__message">
                  <%= @profile.career %>
                </p>
              </div>
            <div class="profile__body">
              <div class="profile__detail">
                <p class="detail__title">お客様へのメッセージ</p>
                <p class="detail__message">
                  <%= @profile.message %>
                </p>
              </div>
            </div>
      </div>
    </div>
     
    </div>
  </div>
</main>